// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Yusuf Al-Bazian
//! The Codex config profile Redline launches its plan sessions under.
//!
//! A Claude plan session gets the round-trip contract from the
//! `redline-plan-review` skill, loaded on demand. Codex has no equivalent on
//! this path: skills are installed under `~/.codex/skills` but *enablement* is
//! a separate, unverified axis, and there is no `Skill` tool. So the contract
//! is delivered as `developer_instructions` — a real top-level Codex config
//! key, verified string-typed.
//!
//! **Why a file and not a `-c` flag.** It was a `-c` flag first, and the
//! command it produced was 6,476 bytes. The macOS tty input queue is 1024
//! bytes, so the launch reached zsh truncated at byte 1023 and sat there
//! unexecuted — see `pty::PTY_CHUNK`. Pacing the write fixes the general case;
//! this fixes the specific one, by making the command ~200 bytes instead.
//! `codex -p <name>` layers `$CODEX_HOME/<name>.config.toml` over the user's
//! own config, and `codex resume -p <name>` layers the same file (both
//! verified against 0.149.0-alpha.4.3).
//!
//! **Why this needs a readiness item.** `-p` with no such file is not an
//! error — Codex ignores it silently. A launch would then run with no contract
//! at all: it would plan, look fine, and destroy the diff on the first
//! revision. So the profile is INSTALLED like the hook and PROBED like the
//! skill, and a missing or stale one blocks the door.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;

/// The contract, generated from `skills/redline-plan-review/SKILL.md` by
/// `scripts/gen-codex-contract.mjs` so the two cannot drift.
pub const CONTRACT: &str = include_str!("codex_plan_contract.txt");

/// The profile name, passed as `codex -p <PROFILE>`. Mirrored in
/// `src/lib/planLaunchCommand.ts` — `launchInvariants.test.ts` pins that they
/// agree, because a mismatch is silent on both sides.
pub const PROFILE: &str = "redline-plan";
const LAUNCHER: &str = include_str!("codex_plan_launch.sh");
const LAUNCHER_NAME: &str = "redline-codex-launch.sh";

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CodexProfileStatus {
    /// The file exists and parses as ours.
    pub installed: bool,
    /// It exists but no longer matches the contract this build ships — the
    /// skill it is generated from moved. Distinct from missing because the
    /// failure is different: a stale contract still plans, and then loses the
    /// block-identity sidecars on the revision.
    pub outdated: bool,
    pub path: String,
}

/// `$CODEX_HOME`, else `~/.codex` — the same resolution `codex -p` uses.
pub(crate) fn codex_home() -> PathBuf {
    if let Some(home) = std::env::var_os("CODEX_HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
    {
        return home;
    }
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".codex")
}

pub fn profile_path() -> PathBuf {
    codex_home().join(format!("{PROFILE}.config.toml"))
}

/// Encode a value as a TOML *basic string*.
///
/// Single-line with `\n` escapes rather than the prettier `"""` form: a
/// multi-line basic string still interprets backslash escapes and still ends
/// early on a stray `"""`, so it would put a content restriction on a file
/// generated from prose somebody else edits. This form has none.
pub fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 32);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // TOML forbids raw control characters in a basic string.
            c if (c as u32) < 0x20 || c as u32 == 0x7f => {
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Exactly what the profile file should contain, for this build.
pub fn expected_contents() -> String {
    format!(
        "# Generated by Redline — do not edit.\n\
         # Selected by `codex -p {PROFILE}`; regenerate from Redline's\n\
         # integration settings. Source: skills/redline-plan-review/SKILL.md\n\
         developer_instructions = {}\n",
        toml_string(CONTRACT)
    )
}

pub fn get_status() -> CodexProfileStatus {
    get_status_at(&profile_path())
}

fn get_status_at(path: &Path) -> CodexProfileStatus {
    let current = fs::read_to_string(path).ok();
    let expected = expected_contents();
    let launcher = path.with_file_name(LAUNCHER_NAME);
    CodexProfileStatus {
        installed: current.is_some(),
        // Byte comparison, not a version field: the file is generated whole,
        // so "differs" and "stale" are the same question and there is nothing
        // to keep in sync.
        outdated: current.is_some_and(|text| text != expected
            || fs::read_to_string(launcher).ok().as_deref() != Some(LAUNCHER)),
        path: path.to_string_lossy().into_owned(),
    }
}

pub fn install() -> Result<CodexProfileStatus, String> {
    install_at(&profile_path())
}

fn install_at(path: &Path) -> Result<CodexProfileStatus, String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    // Whole-file write, unlike the hook install: this file is ours alone (a
    // name nobody else would pick, in a directory of per-profile files), so
    // there is no foreign content to merge and preserve.
    fs::write(path, expected_contents()).map_err(|e| e.to_string())?;
    fs::write(path.with_file_name(LAUNCHER_NAME), LAUNCHER).map_err(|e| e.to_string())?;
    Ok(get_status_at(path))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "redline-codex-profile-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn install_is_idempotent_and_detects_a_hand_edit() {
        let dir = temp_dir();
        let path = dir.join("redline-plan.config.toml");

        assert!(!get_status_at(&path).installed, "nothing there yet");
        let s = install_at(&path).unwrap();
        assert!(s.installed && !s.outdated);
        assert!(!install_at(&path).unwrap().outdated, "re-install is a no-op");

        fs::write(&path, "developer_instructions = \"nope\"\n").unwrap();
        let s = get_status_at(&path);
        assert!(s.installed, "still a file");
        assert!(s.outdated, "…but not the contract this build ships");

        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn the_file_is_valid_toml_carrying_the_whole_contract() {
        let text = expected_contents();
        let value: toml::Value = toml::from_str(&text).expect("must parse as TOML");
        let delivered = value
            .get("developer_instructions")
            .and_then(toml::Value::as_str)
            .expect("developer_instructions must be a string");
        // Byte-for-byte: this is the ONLY delivery of the contract, so a
        // round-trip that drops a newline drops part of the contract.
        assert_eq!(delivered, CONTRACT);
    }

    #[test]
    fn missing_or_stale_launcher_requires_integration_update() {
        let dir = temp_dir();
        let path = dir.join("redline-plan.config.toml");
        install_at(&path).unwrap();
        let launcher = dir.join(LAUNCHER_NAME);
        fs::remove_file(&launcher).unwrap();
        assert!(get_status_at(&path).outdated);
        install_at(&path).unwrap();
        assert_eq!(fs::read_to_string(&launcher).unwrap(), LAUNCHER);
        fs::write(&launcher, "stale launcher").unwrap();
        assert!(get_status_at(&path).outdated);
        assert!(!install_at(&path).unwrap().outdated);
        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn the_contract_carries_both_halves() {
        // The plan half fails loudly (no plan is ever captured). The revision
        // half fails SILENTLY: v1 looks perfect and v2 paints the whole
        // document as changed. Both are asserted here and in the generator.
        assert!(CONTRACT.contains("<proposed_plan>"));
        assert!(CONTRACT.contains("rl:blk-"));
        assert!(CONTRACT.contains("preserve every"));
        assert!(CONTRACT.contains("REDLINE_RESOLUTIONS"));
        assert!(CONTRACT.contains("Do not skip any."));
        // And nothing Claude-only: telling a model to call a tool it does not
        // have ends the turn in confusion instead of a plan.
        assert!(!CONTRACT.contains("ExitPlanMode"));
        assert!(!CONTRACT.contains("/v1/sessions/"));
    }

    #[test]
    fn toml_escaping_survives_the_awkward_characters() {
        for raw in [
            "plain",
            "a\nb",
            "quote \" here",
            "back \\ slash",
            "tab\there",
            "control\u{7}char",
            "\"\"\"not a delimiter\"\"\"",
        ] {
            let doc = format!("k = {}\n", toml_string(raw));
            let v: toml::Value = toml::from_str(&doc).unwrap_or_else(|e| panic!("{raw:?}: {e}"));
            assert_eq!(v["k"].as_str().unwrap(), raw);
        }
    }
}
